// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegracaoGatewayPagamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626094404_AdicionarForeignKeyCobranca")]
    partial class AdicionarForeignKeyCobranca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegracaoGatewayPagamento.DTO.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("IntegracaoGatewayPagamento.DTO.Cobranca", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("billingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("dueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("idCliente")
                        .HasColumnType("uuid");

                    b.Property<string>("invoiceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("paymentDate")
                        .HasColumnType("date");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.Property<double>("value")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("idCliente");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("IntegracaoGatewayPagamento.DTO.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Preco")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("IntegracaoGatewayPagamento.DTO.Cobranca", b =>
                {
                    b.HasOne("IntegracaoGatewayPagamento.DTO.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
